In [26]:
import pandas as pd
df = pd.read_excel('EntriesGender.xlsx')
df = df.sort_values('Total',ascending=False)
df

               Discipline  Female  Male  Total
4               Athletics     969  1072   2041
36               Swimming     361   418    779
20               Football     264   344    608
29                 Rowing     257   265    522
24                   Judo     192   201    393
23                 Hockey     192   192    384
32               Shooting     178   178    356
31                Sailing     175   175    350
22               Handball     168   168    336
30           Rugby Sevens     146   151    297
45              Wrestling      96   193    289
9                  Boxing     102   187    289
42             Volleyball     144   144    288
7              Basketball     144   144    288
43             Water Polo     122   146    268
11           Canoe Sprint     123   126    249
6       Baseball/Softball      90   144    234
19                Fencing     107   108    215
15           Cycling Road      70   131    201
18             Equestrian      73   125    198
44          Weightlifting      98    99    197
2     Artistic Gymnastics      98    98    196
39                 Tennis      94    97    191
16          Cycling Track      90    99    189
5               Badminton      86    87    173
37           Table Tennis      86    86    172
17                 Diving      72    71    143
38              Taekwondo      65    65    130
1                 Archery      64    64    128
21                   Golf      60    60    120
41              Triathlon      55    55    110
3       Artistic Swimming     105     0    105
28    Rhythmic Gymnastics      96     0     96
8        Beach Volleyball      48    48     96
25                 Karate      40    42     82
10           Canoe Slalom      41    41     82
33          Skateboarding      40    40     80
14  Cycling Mountain Bike      38    38     76
27      Modern Pentathlon      36    36     72
0          3x3 Basketball      32    32     64
26      Marathon Swimming      25    25     50
13     Cycling BMX Racing      24    24     48
34         Sport Climbing      20    20     40
35                Surfing      20    20     40
40  Trampoline Gymnastics      16    16     32
12  Cycling BMX Freestyle      10     9     19

In [27]:
male = (
    df.loc[:, ['Discipline', 'Male']]

)
male_age = male['Discipline'].to_list()  # 项目
male_people = male['Male'].to_list()  # 人数

In [28]:
female = (
    df.loc[:, ['Discipline', 'Female']]

)
female_age = female['Discipline'].to_list()  # 项目
female_people = female['Female'].to_list()  # 人数

In [29]:
male_val = []
for a, m in zip(male_age, male_people):
    male_val.append({"year": 2022, "age": a, "sex": 1, "people": m})
male_val

[{'year': 2022, 'age': 'Athletics', 'sex': 1, 'people': 1072},
 {'year': 2022, 'age': 'Swimming', 'sex': 1, 'people': 418},
 {'year': 2022, 'age': 'Football', 'sex': 1, 'people': 344},
 {'year': 2022, 'age': 'Rowing', 'sex': 1, 'people': 265},
 {'year': 2022, 'age': 'Judo', 'sex': 1, 'people': 201},
 {'year': 2022, 'age': 'Hockey', 'sex': 1, 'people': 192},
 {'year': 2022, 'age': 'Shooting', 'sex': 1, 'people': 178},
 {'year': 2022, 'age': 'Sailing', 'sex': 1, 'people': 175},
 {'year': 2022, 'age': 'Handball', 'sex': 1, 'people': 168},
 {'year': 2022, 'age': 'Rugby Sevens', 'sex': 1, 'people': 151},
 {'year': 2022, 'age': 'Wrestling', 'sex': 1, 'people': 193},
 {'year': 2022, 'age': 'Boxing', 'sex': 1, 'people': 187},
 {'year': 2022, 'age': 'Volleyball', 'sex': 1, 'people': 144},
 {'year': 2022, 'age': 'Basketball', 'sex': 1, 'people': 144},
 {'year': 2022, 'age': 'Water Polo', 'sex': 1, 'people': 146},
 {'year': 2022, 'age': 'Canoe Sprint', 'sex': 1, 'people': 126},
 {'year': 2022, 'age': 'Baseball/Softball', 'sex': 1, 'people': 144},
 {'year': 2022, 'age': 'Fencing', 'sex': 1, 'people': 108},
 {'year': 2022, 'age': 'Cycling Road', 'sex': 1, 'people': 131},
 {'year': 2022, 'age': 'Equestrian', 'sex': 1, 'people': 125},
 {'year': 2022, 'age': 'Weightlifting', 'sex': 1, 'people': 99},
 {'year': 2022, 'age': 'Artistic Gymnastics', 'sex': 1, 'people': 98},
 {'year': 2022, 'age': 'Tennis', 'sex': 1, 'people': 97},
 {'year': 2022, 'age': 'Cycling Track', 'sex': 1, 'people': 99},
 {'year': 2022, 'age': 'Badminton', 'sex': 1, 'people': 87},
 {'year': 2022, 'age': 'Table Tennis', 'sex': 1, 'people': 86},
 {'year': 2022, 'age': 'Diving', 'sex': 1, 'people': 71},
 {'year': 2022, 'age': 'Taekwondo', 'sex': 1, 'people': 65},
 {'year': 2022, 'age': 'Archery', 'sex': 1, 'people': 64},
 {'year': 2022, 'age': 'Golf', 'sex': 1, 'people': 60},
 {'year': 2022, 'age': 'Triathlon', 'sex': 1, 'people': 55},
 {'year': 2022, 'age': 'Artistic Swimming', 'sex': 1, 'people': 0},
 {'year': 2022, 'age': 'Rhythmic Gymnastics', 'sex': 1, 'people': 0},
 {'year': 2022, 'age': 'Beach Volleyball', 'sex': 1, 'people': 48},
 {'year': 2022, 'age': 'Karate', 'sex': 1, 'people': 42},
 {'year': 2022, 'age': 'Canoe Slalom', 'sex': 1, 'people': 41},
 {'year': 2022, 'age': 'Skateboarding', 'sex': 1, 'people': 40},
 {'year': 2022, 'age': 'Cycling Mountain Bike', 'sex': 1, 'people': 38},
 {'year': 2022, 'age': 'Modern Pentathlon', 'sex': 1, 'people': 36},
 {'year': 2022, 'age': '3x3 Basketball', 'sex': 1, 'people': 32},
 {'year': 2022, 'age': 'Marathon Swimming', 'sex': 1, 'people': 25},
 {'year': 2022, 'age': 'Cycling BMX Racing', 'sex': 1, 'people': 24},
 {'year': 2022, 'age': 'Sport Climbing', 'sex': 1, 'people': 20},
 {'year': 2022, 'age': 'Surfing', 'sex': 1, 'people': 20},
 {'year': 2022, 'age': 'Trampoline Gymnastics', 'sex': 1, 'people': 16},
 {'year': 2022, 'age': 'Cycling BMX Freestyle', 'sex': 1, 'people': 9}]

In [30]:
female_val = []
for a, f in zip(female_age, female_people):
    female_val.append({"year": 2022, "age": a, "sex": 2, "people": f})
female_val

[{'year': 2022, 'age': 'Athletics', 'sex': 2, 'people': 969},
 {'year': 2022, 'age': 'Swimming', 'sex': 2, 'people': 361},
 {'year': 2022, 'age': 'Football', 'sex': 2, 'people': 264},
 {'year': 2022, 'age': 'Rowing', 'sex': 2, 'people': 257},
 {'year': 2022, 'age': 'Judo', 'sex': 2, 'people': 192},
 {'year': 2022, 'age': 'Hockey', 'sex': 2, 'people': 192},
 {'year': 2022, 'age': 'Shooting', 'sex': 2, 'people': 178},
 {'year': 2022, 'age': 'Sailing', 'sex': 2, 'people': 175},
 {'year': 2022, 'age': 'Handball', 'sex': 2, 'people': 168},
 {'year': 2022, 'age': 'Rugby Sevens', 'sex': 2, 'people': 146},
 {'year': 2022, 'age': 'Wrestling', 'sex': 2, 'people': 96},
 {'year': 2022, 'age': 'Boxing', 'sex': 2, 'people': 102},
 {'year': 2022, 'age': 'Volleyball', 'sex': 2, 'people': 144},
 {'year': 2022, 'age': 'Basketball', 'sex': 2, 'people': 144},
 {'year': 2022, 'age': 'Water Polo', 'sex': 2, 'people': 122},
 {'year': 2022, 'age': 'Canoe Sprint', 'sex': 2, 'people': 123},
 {'year': 2022, 'age': 'Baseball/Softball', 'sex': 2, 'people': 90},
 {'year': 2022, 'age': 'Fencing', 'sex': 2, 'people': 107},
 {'year': 2022, 'age': 'Cycling Road', 'sex': 2, 'people': 70},
 {'year': 2022, 'age': 'Equestrian', 'sex': 2, 'people': 73},
 {'year': 2022, 'age': 'Weightlifting', 'sex': 2, 'people': 98},
 {'year': 2022, 'age': 'Artistic Gymnastics', 'sex': 2, 'people': 98},
 {'year': 2022, 'age': 'Tennis', 'sex': 2, 'people': 94},
 {'year': 2022, 'age': 'Cycling Track', 'sex': 2, 'people': 90},
 {'year': 2022, 'age': 'Badminton', 'sex': 2, 'people': 86},
 {'year': 2022, 'age': 'Table Tennis', 'sex': 2, 'people': 86},
 {'year': 2022, 'age': 'Diving', 'sex': 2, 'people': 72},
 {'year': 2022, 'age': 'Taekwondo', 'sex': 2, 'people': 65},
 {'year': 2022, 'age': 'Archery', 'sex': 2, 'people': 64},
 {'year': 2022, 'age': 'Golf', 'sex': 2, 'people': 60},
 {'year': 2022, 'age': 'Triathlon', 'sex': 2, 'people': 55},
 {'year': 2022, 'age': 'Artistic Swimming', 'sex': 2, 'people': 105},
 {'year': 2022, 'age': 'Rhythmic Gymnastics', 'sex': 2, 'people': 96},
 {'year': 2022, 'age': 'Beach Volleyball', 'sex': 2, 'people': 48},
 {'year': 2022, 'age': 'Karate', 'sex': 2, 'people': 40},
 {'year': 2022, 'age': 'Canoe Slalom', 'sex': 2, 'people': 41},
 {'year': 2022, 'age': 'Skateboarding', 'sex': 2, 'people': 40},
 {'year': 2022, 'age': 'Cycling Mountain Bike', 'sex': 2, 'people': 38},
 {'year': 2022, 'age': 'Modern Pentathlon', 'sex': 2, 'people': 36},
 {'year': 2022, 'age': '3x3 Basketball', 'sex': 2, 'people': 32},
 {'year': 2022, 'age': 'Marathon Swimming', 'sex': 2, 'people': 25},
 {'year': 2022, 'age': 'Cycling BMX Racing', 'sex': 2, 'people': 24},
 {'year': 2022, 'age': 'Sport Climbing', 'sex': 2, 'people': 20},
 {'year': 2022, 'age': 'Surfing', 'sex': 2, 'people': 20},
 {'year': 2022, 'age': 'Trampoline Gymnastics', 'sex': 2, 'people': 16},
 {'year': 2022, 'age': 'Cycling BMX Freestyle', 'sex': 2, 'people': 10}]

In [31]:
val = female_val + male_val
val

[{'year': 2022, 'age': 'Athletics', 'sex': 2, 'people': 969},
 {'year': 2022, 'age': 'Swimming', 'sex': 2, 'people': 361},
 {'year': 2022, 'age': 'Football', 'sex': 2, 'people': 264},
 {'year': 2022, 'age': 'Rowing', 'sex': 2, 'people': 257},
 {'year': 2022, 'age': 'Judo', 'sex': 2, 'people': 192},
 {'year': 2022, 'age': 'Hockey', 'sex': 2, 'people': 192},
 {'year': 2022, 'age': 'Shooting', 'sex': 2, 'people': 178},
 {'year': 2022, 'age': 'Sailing', 'sex': 2, 'people': 175},
 {'year': 2022, 'age': 'Handball', 'sex': 2, 'people': 168},
 {'year': 2022, 'age': 'Rugby Sevens', 'sex': 2, 'people': 146},
 {'year': 2022, 'age': 'Wrestling', 'sex': 2, 'people': 96},
 {'year': 2022, 'age': 'Boxing', 'sex': 2, 'people': 102},
 {'year': 2022, 'age': 'Volleyball', 'sex': 2, 'people': 144},
 {'year': 2022, 'age': 'Basketball', 'sex': 2, 'people': 144},
 {'year': 2022, 'age': 'Water Polo', 'sex': 2, 'people': 122},
 {'year': 2022, 'age': 'Canoe Sprint', 'sex': 2, 'people': 123},
 {'year': 2022, 'age': 'Baseball/Softball', 'sex': 2, 'people': 90},
 {'year': 2022, 'age': 'Fencing', 'sex': 2, 'people': 107},
 {'year': 2022, 'age': 'Cycling Road', 'sex': 2, 'people': 70},
 {'year': 2022, 'age': 'Equestrian', 'sex': 2, 'people': 73},
 {'year': 2022, 'age': 'Weightlifting', 'sex': 2, 'people': 98},
 {'year': 2022, 'age': 'Artistic Gymnastics', 'sex': 2, 'people': 98},
 {'year': 2022, 'age': 'Tennis', 'sex': 2, 'people': 94},
 {'year': 2022, 'age': 'Cycling Track', 'sex': 2, 'people': 90},
 {'year': 2022, 'age': 'Badminton', 'sex': 2, 'people': 86},
 {'year': 2022, 'age': 'Table Tennis', 'sex': 2, 'people': 86},
 {'year': 2022, 'age': 'Diving', 'sex': 2, 'people': 72},
 {'year': 2022, 'age': 'Taekwondo', 'sex': 2, 'people': 65},
 {'year': 2022, 'age': 'Archery', 'sex': 2, 'people': 64},
 {'year': 2022, 'age': 'Golf', 'sex': 2, 'people': 60},
 {'year': 2022, 'age': 'Triathlon', 'sex': 2, 'people': 55},
 {'year': 2022, 'age': 'Artistic Swimming', 'sex': 2, 'people': 105},
 {'year': 2022, 'age': 'Rhythmic Gymnastics', 'sex': 2, 'people': 96},
 {'year': 2022, 'age': 'Beach Volleyball', 'sex': 2, 'people': 48},
 {'year': 2022, 'age': 'Karate', 'sex': 2, 'people': 40},
 {'year': 2022, 'age': 'Canoe Slalom', 'sex': 2, 'people': 41},
 {'year': 2022, 'age': 'Skateboarding', 'sex': 2, 'people': 40},
 {'year': 2022, 'age': 'Cycling Mountain Bike', 'sex': 2, 'people': 38},
 {'year': 2022, 'age': 'Modern Pentathlon', 'sex': 2, 'people': 36},
 {'year': 2022, 'age': '3x3 Basketball', 'sex': 2, 'people': 32},
 {'year': 2022, 'age': 'Marathon Swimming', 'sex': 2, 'people': 25},
 {'year': 2022, 'age': 'Cycling BMX Racing', 'sex': 2, 'people': 24},
 {'year': 2022, 'age': 'Sport Climbing', 'sex': 2, 'people': 20},
 {'year': 2022, 'age': 'Surfing', 'sex': 2, 'people': 20},
 {'year': 2022, 'age': 'Trampoline Gymnastics', 'sex': 2, 'people': 16},
 {'year': 2022, 'age': 'Cycling BMX Freestyle', 'sex': 2, 'people': 10},
 {'year': 2022, 'age': 'Athletics', 'sex': 1, 'people': 1072},
 {'year': 2022, 'age': 'Swimming', 'sex': 1, 'people': 418},
 {'year': 2022, 'age': 'Football', 'sex': 1, 'people': 344},
 {'year': 2022, 'age': 'Rowing', 'sex': 1, 'people': 265},
 {'year': 2022, 'age': 'Judo', 'sex': 1, 'people': 201},
 {'year': 2022, 'age': 'Hockey', 'sex': 1, 'people': 192},
 {'year': 2022, 'age': 'Shooting', 'sex': 1, 'people': 178},
 {'year': 2022, 'age': 'Sailing', 'sex': 1, 'people': 175},
 {'year': 2022, 'age': 'Handball', 'sex': 1, 'people': 168},
 {'year': 2022, 'age': 'Rugby Sevens', 'sex': 1, 'people': 151},
 {'year': 2022, 'age': 'Wrestling', 'sex': 1, 'people': 193},
 {'year': 2022, 'age': 'Boxing', 'sex': 1, 'people': 187},
 {'year': 2022, 'age': 'Volleyball', 'sex': 1, 'people': 144},
 {'year': 2022, 'age': 'Basketball', 'sex': 1, 'people': 144},
 {'year': 2022, 'age': 'Water Polo', 'sex': 1, 'people': 146},
 {'year': 2022, 'age': 'Canoe Sprint', 'sex': 1, 'people': 126},
 {'year': 2022, 'age': 'Baseball/Softball', 'sex': 1, 'people': 144},
 {'year': 2022, 'age': 'Fencing', 'sex': 1, 'people': 108},
 {'year': 2022, 'age': 'Cycling Road', 'sex': 1, 'people': 131},
 {'year': 2022, 'age': 'Equestrian', 'sex': 1, 'people': 125},
 {'year': 2022, 'age': 'Weightlifting', 'sex': 1, 'people': 99},
 {'year': 2022, 'age': 'Artistic Gymnastics', 'sex': 1, 'people': 98},
 {'year': 2022, 'age': 'Tennis', 'sex': 1, 'people': 97},
 {'year': 2022, 'age': 'Cycling Track', 'sex': 1, 'people': 99},
 {'year': 2022, 'age': 'Badminton', 'sex': 1, 'people': 87},
 {'year': 2022, 'age': 'Table Tennis', 'sex': 1, 'people': 86},
 {'year': 2022, 'age': 'Diving', 'sex': 1, 'people': 71},
 {'year': 2022, 'age': 'Taekwondo', 'sex': 1, 'people': 65},
 {'year': 2022, 'age': 'Archery', 'sex': 1, 'people': 64},
 {'year': 2022, 'age': 'Golf', 'sex': 1, 'people': 60},
 {'year': 2022, 'age': 'Triathlon', 'sex': 1, 'people': 55},
 {'year': 2022, 'age': 'Artistic Swimming', 'sex': 1, 'people': 0},
 {'year': 2022, 'age': 'Rhythmic Gymnastics', 'sex': 1, 'people': 0},
 {'year': 2022, 'age': 'Beach Volleyball', 'sex': 1, 'people': 48},
 {'year': 2022, 'age': 'Karate', 'sex': 1, 'people': 42},
 {'year': 2022, 'age': 'Canoe Slalom', 'sex': 1, 'people': 41},
 {'year': 2022, 'age': 'Skateboarding', 'sex': 1, 'people': 40},
 {'year': 2022, 'age': 'Cycling Mountain Bike', 'sex': 1, 'people': 38},
 {'year': 2022, 'age': 'Modern Pentathlon', 'sex': 1, 'people': 36},
 {'year': 2022, 'age': '3x3 Basketball', 'sex': 1, 'people': 32},
 {'year': 2022, 'age': 'Marathon Swimming', 'sex': 1, 'people': 25},
 {'year': 2022, 'age': 'Cycling BMX Racing', 'sex': 1, 'people': 24},
 {'year': 2022, 'age': 'Sport Climbing', 'sex': 1, 'people': 20},
 {'year': 2022, 'age': 'Surfing', 'sex': 1, 'people': 20},
 {'year': 2022, 'age': 'Trampoline Gymnastics', 'sex': 1, 'people': 16},
 {'year': 2022, 'age': 'Cycling BMX Freestyle', 'sex': 1, 'people': 9}]

In [32]:
import json
with open('数据.json', 'w') as f:
    f.write(json.dumps(val))

In [36]:
from pyecharts import options as opts
from pyecharts.charts import Map
from pyecharts.faker import Faker

c = (
    Map()
    .add("商家A", [list(z) for z in zip(Faker.provinces, Faker.values())], "china")
    .set_global_opts(title_opts=opts.TitleOpts(title="Map-基本示例"))
    .render("map_base.html")
)

In [ ]:
from pyecharts import options as opts
from pyecharts.charts import Map
from pyecharts.faker import Faker

c = (
    Map()
    .add("商家A", [list(z) for z in zip(Faker.country, Faker.values())], "world")
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Map-世界地图"),
        visualmap_opts=opts.VisualMapOpts(max_=200),
    )
    .render("map_world.html")
)